import type { ActivityLog, AppSettings, ContactLog, Creator, Product, Template } from "@/types/db";

export const appSettings: AppSettings = {
  brand: {
    enterprise_name: "Vesure Enterprise",
    mcn_name: "VesureMedia",
  },
  commission: {
    default_rate: "7%",
  },
  follow_up_days: {
    first: 7,
    second: 30,
    sample_reminder_1: 3,
    sample_reminder_2: 7,
  },
};

export const products: Product[] = [
  {
    id: "prod-1",
    name: "Swiss Thomas",
    category: "Health",
    description: "Trusted health product for creator promotion",
    links: [
      { label: "Product 1", url: "https://affiliate.tiktok.com/api/v1/share/ALJgz1BTA6Pk" },
      { label: "Product 2", url: "https://affiliate.tiktok.com/api/v1/share/ALJgz1OMGNz8" },
      { label: "Product 3", url: "https://affiliate.tiktok.com/api/v1/share/ALJgz1BTRIQG" },
    ],
    commission_rate: "7%",
    is_active: true,
    created_at: "2025-01-10T00:00:00Z",
    updated_at: "2025-01-10T00:00:00Z",
  },
  {
    id: "prod-2",
    name: "Glow + Balance",
    category: "Beauty",
    description: "Skincare routine for everyday creator content.",
    links: [
      { label: "Shop", url: "https://example.com/glow-shop" },
      { label: "Link 2", url: "https://example.com/glow-link" },
    ],
    commission_rate: "10%",
    is_active: true,
    created_at: "2025-01-12T00:00:00Z",
    updated_at: "2025-01-12T00:00:00Z",
  },
];

export const templates: Template[] = [
  {
    id: "tpl-1",
    name: "Vesure Enterprise Invite",
    type: "Product Collaboration",
    category: "Health",
    channel: "WhatsApp",
    language: "EN",
    body: "Hi {{creator_name}}! 👋✨\n\nWe love your content and would like to invite you to collaborate with {{brand_name}}! 💙\n\nPromote our trusted products {{product_name}} and enjoy:\n💰 {{commission_rate}} Commission\n🎁 Free Samples\n📢 Free Ads Support\n\nView products here:\n{{product_links}}\n\nIf you're interested, just let us know! 🤝✨\nWe'd love to work with you! 💙",
    is_active: true,
    created_at: "2025-01-01T00:00:00Z",
    updated_at: "2025-01-01T00:00:00Z",
  },
  {
    id: "tpl-2",
    name: "VesureMedia MCN Invite",
    type: "MCN Invite",
    category: "Health",
    channel: "WhatsApp",
    language: "EN",
    body: "Hi {{creator_name}}! 👋\n\nWe're from {{mcn_name}}, and we've been following your content. We really enjoy what you're creating and believe you'd be a great fit for our MCN.\n\nWe help creators grow with:\n📈 Dedicated support\n💰 Monetization guidance\n🎬 Content strategies\n🤝 Exciting brand collaboration opportunities\n\nWe'd love to have you join our creator community and support your journey. Let us know if you're interested—we'd be happy to share more details!",
    is_active: true,
    created_at: "2025-01-01T00:00:00Z",
    updated_at: "2025-01-01T00:00:00Z",
  },
  {
    id: "tpl-3",
    name: "Follow-up 1 (7 Days)",
    type: "Follow-up",
    category: "Health",
    channel: "WhatsApp",
    language: "EN",
    body: "Hi {{creator_name}}! 👋\n\nJust following up on our earlier message — we'd really love to have you join our creator community. 💙\n\nWe've helped creators like you grow with monetization support, brand deals, and content guidance. No pressure at all — just wanted to make sure you saw our message!\n\nLet us know if you'd like more details. 🤝",
    is_active: true,
    created_at: "2025-01-01T00:00:00Z",
    updated_at: "2025-01-01T00:00:00Z",
  },
  {
    id: "tpl-4",
    name: "Follow-up 2 (30 Days)",
    type: "Follow-up",
    category: "Health",
    channel: "WhatsApp",
    language: "EN",
    body: "Hi {{creator_name}}! 👋\n\nWe reached out about a month ago — just checking in one last time. We're still very interested in working with you! 💙\n\nIf the timing wasn't right before, we'd love to reconnect. Our door is always open.\n\nReply \"YES\" if you'd like to hear more, or \"NO\" and we won't follow up again. Either way, we appreciate your content! 🙏",
    is_active: true,
    created_at: "2025-01-01T00:00:00Z",
    updated_at: "2025-01-01T00:00:00Z",
  },
  {
    id: "tpl-5",
    name: "Sample Sent Notification",
    type: "Sample",
    category: "Health",
    channel: "WhatsApp",
    language: "EN",
    body: "Hi {{creator_name}}! 📦✨\n\nGreat news — your free sample has been shipped!\n\nProduct: {{product_name}}\nTracking: {{tracking_number}}\n\nOnce you receive it, feel free to start creating content whenever you're ready. We can't wait to see what you make! 💙",
    is_active: true,
    created_at: "2025-01-01T00:00:00Z",
    updated_at: "2025-01-01T00:00:00Z",
  },
  {
    id: "tpl-6",
    name: "Sample Reminder (Day 3)",
    type: "Sample",
    category: "Health",
    channel: "WhatsApp",
    language: "EN",
    body: "Hi {{creator_name}}! 👋\n\nHope you received your sample! Just checking in — how's the product so far? 😊\n\nIf you need any content ideas or guidance, just let us know. We're here to help! 💙",
    is_active: true,
    created_at: "2025-01-01T00:00:00Z",
    updated_at: "2025-01-01T00:00:00Z",
  },
  {
    id: "tpl-7",
    name: "Sample Reminder (Day 7)",
    type: "Sample",
    category: "Health",
    channel: "WhatsApp",
    language: "EN",
    body: "Hi {{creator_name}}! ⏰\n\nJust a friendly reminder — we'd love to see your content whenever you're ready! 🎬\n\nPosting within 7 days helps you unlock:\n✅ Priority for future samples\n✅ Higher commission tier\n✅ Featured on our brand page\n\nLet us know if you need anything! 💙",
    is_active: true,
    created_at: "2025-01-01T00:00:00Z",
    updated_at: "2025-01-01T00:00:00Z",
  },
];

export const creators: Creator[] = [
  {
    id: "cre-1",
    creator_name: "Alicia Tan",
    tiktok_handle: "@aliciatan",
    whatsapp_number: "+60123456789",
    email: "alicia@example.com",
    category: "Beauty",
    follower_count: 68400,
    engagement_rate: 7.8,
    source: "Kalopilot",
    status: "Invited",
    product_id: "prod-1",
    pic: "Nadia",
    notes: "Interested in skincare collaborations.",
    last_contact_at: "2025-07-09T10:00:00Z",
    created_at: "2025-06-20T12:00:00Z",
    updated_at: "2025-07-09T10:00:00Z",
  },
  {
    id: "cre-2",
    creator_name: "Misha Lee",
    tiktok_handle: "@mishafit",
    whatsapp_number: "+60122223333",
    email: "misha@example.com",
    category: "Health",
    follower_count: 232000,
    engagement_rate: 11.4,
    source: "Manual",
    status: "Replied",
    product_id: "prod-1",
    pic: "Yasmin",
    notes: "Wants to try product before committing.",
    last_contact_at: "2025-07-15T08:00:00Z",
    created_at: "2025-06-25T09:00:00Z",
    updated_at: "2025-07-15T08:00:00Z",
  },
  {
    id: "cre-3",
    creator_name: "Zara Malik",
    tiktok_handle: "@zaramalik",
    whatsapp_number: "+60123334444",
    email: "zara@example.com",
    category: "Fashion",
    follower_count: 124000,
    engagement_rate: 6.9,
    source: "Referral",
    status: "Active",
    product_id: "prod-2",
    pic: "Aisha",
    notes: "Consistent content and repeat deliveries.",
    last_contact_at: "2025-07-20T09:30:00Z",
    created_at: "2025-06-21T12:00:00Z",
    updated_at: "2025-07-20T09:30:00Z",
  },
  {
    id: "cre-4",
    creator_name: "Nina Rahman",
    tiktok_handle: "@ninarahman",
    whatsapp_number: "+60129998888",
    email: "nina@example.com",
    category: "Food",
    follower_count: 81200,
    engagement_rate: 9.4,
    source: "Competitor Mining",
    status: "Not Contacted",
    product_id: "prod-1",
    pic: "Nadia",
    notes: "Potential for food review content.",
    last_contact_at: "2025-06-10T14:00:00Z",
    created_at: "2025-06-18T16:00:00Z",
    updated_at: "2025-06-10T14:00:00Z",
  },
];

export const activityLog: ActivityLog[] = [
  {
    id: "act-1",
    creator_id: "cre-1",
    action: "Status update",
    old_value: "Not Contacted",
    new_value: "Invited",
    performed_by: "System",
    created_at: "2025-07-09T10:00:00Z",
  },
  {
    id: "act-2",
    creator_id: "cre-2",
    action: "Sent message",
    old_value: null,
    new_value: "Follow-up 1 Sent",
    performed_by: "Ops Team",
    created_at: "2025-07-15T08:00:00Z",
  },
  {
    id: "act-3",
    creator_id: "cre-3",
    action: "Assigned product",
    old_value: "prod-1",
    new_value: "prod-2",
    performed_by: "Ops Team",
    created_at: "2025-07-20T09:30:00Z",
  },
];

export const contactLog: ContactLog[] = [
  {
    id: "log-1",
    creator_id: "cre-1",
    channel: "WhatsApp",
    template_id: "tpl-1",
    message_body: "Hi Alicia! We would love to work with you.",
    sent_at: "2025-07-09T10:00:00Z",
    replied: true,
    replied_at: "2025-07-10T12:00:00Z",
    reply_body: "Thanks! We are interested.",
  },
  {
    id: "log-2",
    creator_id: "cre-2",
    channel: "WhatsApp",
    template_id: "tpl-3",
    message_body: "Hi Misha! Just following up.",
    sent_at: "2025-07-15T08:00:00Z",
    replied: false,
    replied_at: null,
    reply_body: null,
  },
];
